apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed-images
spec:
  validationFailureAction: enforce
  background: false
  rules:
    - name: check-signature
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
        - image: "ghcr.io/kiku99/*"
          keyless:
            issuer: "https://token.actions.githubusercontent.com"
            subject: "https://github.com/kiku99/.*"