apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-signed-images
spec:
  validationFailureAction: Enforce
  background: false
  rules:
    - name: check-signature
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
        - imageReferences:
            - "kiku99/slsa*"
            - "docker.io/kiku99/slsa*"
          required: true
          verifyDigest: true
          attestors:
            - entries:
                - keyless:
                    rekor:
                      url: https://rekor.sigstore.dev
                    issuer: "https://token.actions.githubusercontent.com"
                    subject: "https://github.com/kiku99/slsa/.github/workflows/build-sign.yaml@refs/heads/main"