apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-demo
  namespace: slsa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-demo
  template:
    metadata:
      labels:
        app: slsa-demo
    spec:
      containers:
        - name: app
          image: kiku99/slsa:sha-36970ea1c97d7213bac2d7585cb6c38031d6186a
          ports:
            - containerPort: 8080 