apiVersion: apps/v1
kind: Deployment
metadata:
  name: slsa-demo
  namespace: slsa-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slsa-demo
  template:
    metadata:
      labels:
        app: slsa-demo
    spec:
      containers:
        - name: app
          image: kiku99/slsa:sha-0f8f692e2b7421fefcb29dbafa056ef9954b319f
          ports:
            - containerPort: 8080 